port = 8080
tlsPort = 10443 
tlsDir = "./tls"

plugins = [
	"github.com/user/repo as csv",
]

include = [
	"./env.toml",
	"./routes/api.toml",

]

[[flag]]
name = "seed"
defaultValue = "false"
usage = "Set to true when you want to re-seed the service"
